channels:
  - pytorch
  - conda-forge
dependencies:
  - numpy=1.21.2
  - pandas=1.3.3
  - scipy=1.7.1
  - scikit-learn=1.0
  - jupyter=1.0.0
  - seaborn=0.11.2
  - pytorch=1.10.0
  - tokenizers=0.10.3
  - pyyaml=5.4.1
  - matplotlib=3.4.3
  - pip:
      - allennlp
      - tensorboard
      - datasets==1.12.1
      - transformers==4.5.1
      - pyarrow==5.0.0
      - pep8==1.7.1
      - pylint==2.12.2
      - spacy==3.1.3
      - rich==10.15.2
name: py39-gqa
